// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHdPGpuhYSScNrDqjL_Yew9iiKhdebE0',
    appId: '1:868981807041:web:035f79fc6b8404c8fec140',
    messagingSenderId: '868981807041',
    projectId: 'chaos-app-4dd51',
    authDomain: 'chaos-app-4dd51.firebaseapp.com',
    storageBucket: 'chaos-app-4dd51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPkwq13HYs4P8cgW2D_UCNw-trAORoiE',
    appId: '1:868981807041:android:c3695ba0a70cc855fec140',
    messagingSenderId: '868981807041',
    projectId: 'chaos-app-4dd51',
    storageBucket: 'chaos-app-4dd51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCT1sXFIRW1p07JfgOtLFMIsJ58QDoaE',
    appId: '1:868981807041:ios:a06265b72a37d76dfec140',
    messagingSenderId: '868981807041',
    projectId: 'chaos-app-4dd51',
    storageBucket: 'chaos-app-4dd51.firebasestorage.app',
    iosBundleId: 'com.example.chaosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvCT1sXFIRW1p07JfgOtLFMIsJ58QDoaE',
    appId: '1:868981807041:ios:a06265b72a37d76dfec140',
    messagingSenderId: '868981807041',
    projectId: 'chaos-app-4dd51',
    storageBucket: 'chaos-app-4dd51.firebasestorage.app',
    iosBundleId: 'com.example.chaosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSHdPGpuhYSScNrDqjL_Yew9iiKhdebE0',
    appId: '1:868981807041:web:e1e32a61fe1d7838fec140',
    messagingSenderId: '868981807041',
    projectId: 'chaos-app-4dd51',
    authDomain: 'chaos-app-4dd51.firebaseapp.com',
    storageBucket: 'chaos-app-4dd51.firebasestorage.app',
  );
}
